### ISSUE TITLE
Icons in toolbox do not display.

### ISSUE THREAD

**Issue by sprague252** [lucadem1313/jsTrack#3]
The icons in the Toolbox do not display. Users must hover over each empty icon to see what it is. I have tested this on a Chromebook, a Mac running Chrome, and a Mac running Safari, and I get the same results. See the screenshot below.

![Screen Shot 2020-04-10 at 1 10 15 PM](https://user-images.githubusercontent.com/24415455/79009038-a7126700-7b2c-11ea-9d4c-00fffcaadfe2.png)

**Comment by sprague252** [comment]
I just downloaded the source and ran it on my own server. The icons show up. The issue is with the live version of JSTrack at https://jst.lucademian.com/.

**Comment by lucademian** [comment]
Thanks for alerting me to this, I recently switched from Apache to Nginx on my server and some of the Nginx config was broken. Should be all set now.

**Comment by sprague252** [comment]
Thanks! I put jsTrack on my server for my students to use, but I do not
have the Drive authentication part working. I am going to point students
who need to use Drive to yours. This is a great tool!

-Mark
